const futureStateNames = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
];

const collegeStates = [
  {
    id: "ca",
    name: "California",
    status: "loaded",
    note: "Loaded now: University of California undergraduate campuses only. UCSF is not listed because it is a graduate and professional health-sciences campus without standard first-year undergraduate admission.",
    colleges: [
      {
        id: "uc-berkeley",
        name: "University of California, Berkeley",
        shortName: "UC Berkeley",
        city: "Berkeley",
        region: "San Francisco Bay Area",
        founded: 1868,
        type: "Public research university",
        admission: {
          year: "Fall 2025",
          rate: 11,
          displayRate: "11%",
          applicants: "126,830",
          admitted: "14,360",
          enrolled: "6,688",
        },
        coordinates: { lat: 37.8719, lon: -122.2585 },
        cost: {
          year: "2026-27",
          tuition: "$18,216",
          tuitionNumeric: 18216,
          onCampusHousingFood: "$23,640",
          offCampusHousing: "$14,480",
          offCampusFood: "$6,012",
          totalResident: "$54,470",
          nonResidentSupplement: "$39,270",
          sourceUrl: "https://financialaid.berkeley.edu/how-aid-works/student-budgets-cost-of-attendance/",
        },
        image: "./assets/uc-berkeley.jpg",
        imageAlt: "Sather Tower and Memorial Glade at UC Berkeley",
        imageSource: "https://commons.wikimedia.org/wiki/File:Berkeley_glade_afternoon.jpg",
        summary:
          "The founding UC campus is known for deep research strength, selective admissions, engineering, computing, business, public policy, chemistry, and a dense urban campus beside the Bay Area.",
        programs: [
          "Computer Science",
          "Data Science",
          "Engineering",
          "Business",
          "Chemistry",
          "Economics",
          "Political Science",
          "Architecture",
          "Environmental Science",
          "Molecular & Cell Biology",
        ],
        fit: [
          "Students who want a large research campus with very selective admission",
          "Applicants looking for technology, public service, science, policy, or entrepreneurship paths",
          "Students comfortable with a competitive urban academic environment",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/University_of_California,_Berkeley",
        programsUrl: "https://admissions.berkeley.edu/academics/",
      },
      {
        id: "uc-davis",
        name: "University of California, Davis",
        shortName: "UC Davis",
        city: "Davis",
        region: "Sacramento Valley",
        founded: 1905,
        type: "Public research university",
        admission: {
          year: "Fall 2025",
          rate: 44,
          displayRate: "44%",
          applicants: "102,988",
          admitted: "45,673",
          enrolled: "6,805",
        },
        coordinates: { lat: 38.5382, lon: -121.7617 },
        cost: {
          year: "2026-27",
          tuition: "$18,078",
          tuitionNumeric: 18078,
          onCampusHousingFood: "$22,252",
          offCampusHousingFood: "$16,981",
          totalResident: "$49,009",
          nonResidentTotal: "$88,279",
          sourceUrl: "https://financialaid.ucdavis.edu/undergraduate/cost/2627-entering",
        },
        image: "./assets/uc-davis.jpg",
        imageAlt: "Peter J. Shields Library at UC Davis",
        imageSource: "https://commons.wikimedia.org/wiki/File:UCDavis_PeterJShieldsLibrary.jpg",
        summary:
          "UC Davis combines a large college-town campus with nationally known agriculture, life sciences, veterinary medicine, environmental science, engineering, design, and health-related pathways.",
        programs: [
          "Animal Science",
          "Biological Sciences",
          "Agricultural & Environmental Sciences",
          "Engineering",
          "Computer Science",
          "Design",
          "Economics",
          "Environmental Policy",
          "Viticulture & Enology",
          "Pre-Health",
        ],
        fit: [
          "Students who want a research university with a college-town setting",
          "Applicants interested in agriculture, sustainability, biology, animal science, or health",
          "Students who want strong STEM options with a more spacious campus feel",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/University_of_California,_Davis",
        programsUrl: "https://www.ucdavis.edu/majors",
      },
      {
        id: "uc-irvine",
        name: "University of California, Irvine",
        shortName: "UC Irvine",
        city: "Irvine",
        region: "Orange County",
        founded: 1965,
        type: "Public research university",
        admission: {
          year: "Fall 2025",
          rate: 29,
          displayRate: "29%",
          applicants: "124,231",
          admitted: "35,964",
          enrolled: "6,421",
        },
        coordinates: { lat: 33.6405, lon: -117.8443 },
        cost: {
          year: "2026-27",
          tuition: "$20,077",
          tuitionNumeric: 20077,
          onCampusHousingFood: "$20,926",
          offCampusHousingFood: "$22,419",
          totalResident: "$46,007",
          nonResidentSupplement: "$39,270",
          sourceUrl: "https://www.ofas.uci.edu/cost/undergraduate-costs/new-students.php",
        },
        image: "./assets/uc-irvine.jpg",
        imageAlt: "UC Irvine Student Center",
        imageSource: "https://commons.wikimedia.org/wiki/File:UCI_Student_Center.jpg",
        summary:
          "UC Irvine is a highly selective research campus in Orange County with strong biological sciences, computer science, business, public health, engineering, social ecology, and arts programs.",
        programs: [
          "Biological Sciences",
          "Computer Science",
          "Business Administration",
          "Public Health",
          "Engineering",
          "Criminology",
          "Psychology",
          "Political Science",
          "Nursing",
          "Drama",
        ],
        fit: [
          "Students looking for a planned campus in Southern California",
          "Applicants focused on biology, computing, public health, business, or law-adjacent fields",
          "Students who want research access near Orange County industry and hospitals",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/University_of_California,_Irvine",
        programsUrl: "https://admissions.uci.edu/discover/academics.php",
      },
      {
        id: "ucla",
        name: "University of California, Los Angeles",
        shortName: "UCLA",
        city: "Los Angeles",
        region: "Westwood",
        founded: 1919,
        type: "Public research university",
        admission: {
          year: "Fall 2025",
          rate: 9,
          displayRate: "9%",
          applicants: "145,060",
          admitted: "13,659",
          enrolled: "6,551",
        },
        coordinates: { lat: 34.0689, lon: -118.4452 },
        cost: {
          year: "2026-27",
          tuition: "$16,706",
          tuitionNumeric: 16706,
          onCampusHousingFood: "$19,779",
          offCampusHousingFood: "$21,087",
          totalResident: "$45,353",
          nonResidentTotal: "$84,623",
          sourceUrl: "https://financialaid.ucla.edu/go/coa",
        },
        image: "./assets/ucla.jpg",
        imageAlt: "Powell Library at UCLA",
        imageSource: "https://commons.wikimedia.org/wiki/File:Powell_Library,_UCLA_(10_December_2005).jpg",
        summary:
          "UCLA is one of the most selective public universities in the country, with broad strengths across arts, sciences, engineering, film, business economics, public affairs, medicine, and pre-professional tracks.",
        programs: [
          "Biology",
          "Business Economics",
          "Computer Science",
          "Engineering",
          "Film & Television",
          "Political Science",
          "Psychology",
          "Public Affairs",
          "Neuroscience",
          "Music",
        ],
        fit: [
          "Students aiming for a very selective, high-energy campus in Los Angeles",
          "Applicants seeking strong academics plus arts, media, research, and pre-health options",
          "Students who want a large public university with major city access",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/University_of_California,_Los_Angeles",
        programsUrl: "https://admission.ucla.edu/explore/majors",
      },
      {
        id: "uc-merced",
        name: "University of California, Merced",
        shortName: "UC Merced",
        city: "Merced",
        region: "San Joaquin Valley",
        founded: 2005,
        type: "Public research university",
        admission: {
          year: "Fall 2025",
          rate: 94,
          displayRate: "94%",
          applicants: "49,366",
          admitted: "46,565",
          enrolled: "1,982",
        },
        coordinates: { lat: 37.3656, lon: -120.4247 },
        cost: {
          year: "2026-27",
          tuition: "$16,986",
          tuitionNumeric: 16986,
          onCampusHousingFood: "$23,240",
          offCampusHousingFood: "$14,712",
          totalResident: "$48,498",
          nonResidentTotal: "$88,200",
          sourceUrl: "https://financialaid.ucmerced.edu/cost-attendance",
        },
        image: "./assets/uc-merced.jpg",
        imageAlt: "Kolligian Library at UC Merced",
        imageSource: "https://commons.wikimedia.org/wiki/File:UCM_library.jpg",
        summary:
          "UC Merced is the newest UC campus, with fast-growing research programs, strong access for California students, and strengths in engineering, computer science, biological sciences, cognitive science, and environmental systems.",
        programs: [
          "Computer Science & Engineering",
          "Mechanical Engineering",
          "Biological Sciences",
          "Cognitive Science",
          "Public Health",
          "Environmental Systems",
          "Management & Business Economics",
          "Psychology",
          "Political Science",
          "Applied Mathematics",
        ],
        fit: [
          "Students who want a UC education with a smaller and newer campus feel",
          "Applicants interested in growth, access, research, engineering, or environmental work",
          "Students who want more room to shape campus life and organizations",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/University_of_California,_Merced",
        programsUrl: "https://admissions.ucmerced.edu/academics/majors-minors",
      },
      {
        id: "uc-riverside",
        name: "University of California, Riverside",
        shortName: "UC Riverside",
        city: "Riverside",
        region: "Inland Southern California",
        founded: 1954,
        type: "Public research university",
        admission: {
          year: "Fall 2025",
          rate: 87,
          displayRate: "87%",
          applicants: "70,863",
          admitted: "61,312",
          enrolled: "6,682",
        },
        coordinates: { lat: 33.9737, lon: -117.3281 },
        cost: {
          year: "2026-27",
          tuition: "$16,758",
          tuitionNumeric: 16758,
          onCampusHousingFood: "$21,075",
          offCampusHousingFood: "$17,625",
          totalResident: "$46,367",
          sourceUrl: "https://financialaid.ucr.edu/cost",
        },
        image: "./assets/uc-riverside.jpg",
        imageAlt: "Tomas Rivera Library at UC Riverside",
        imageSource: "https://commons.wikimedia.org/wiki/File:Rivera_Library.JPG",
        summary:
          "UC Riverside is a diverse research university with notable programs in business, engineering, natural and agricultural sciences, public policy, psychology, creative writing, and medicine pathways.",
        programs: [
          "Business",
          "Engineering",
          "Biology",
          "Computer Science",
          "Psychology",
          "Public Policy",
          "Creative Writing",
          "Entomology",
          "Environmental Sciences",
          "Pre-Med",
        ],
        fit: [
          "Students seeking a UC research university with broad access and strong mobility outcomes",
          "Applicants interested in life sciences, engineering, business, public policy, or agriculture-adjacent research",
          "Students who want Southern California without a coastal-campus price or pace",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/University_of_California,_Riverside",
        programsUrl: "https://admissions.ucr.edu/majors",
      },
      {
        id: "uc-san-diego",
        name: "University of California, San Diego",
        shortName: "UC San Diego",
        city: "San Diego",
        region: "La Jolla",
        founded: 1960,
        type: "Public research university",
        admission: {
          year: "Fall 2025",
          rate: 28,
          displayRate: "28%",
          applicants: "136,727",
          admitted: "38,457",
          enrolled: "7,801",
        },
        coordinates: { lat: 32.8801, lon: -117.234 },
        cost: {
          year: "2026-27",
          tuition: "$18,099",
          tuitionNumeric: 18099,
          onCampusHousingFood: "$20,445",
          offCampusHousingFood: "$20,502",
          totalResident: "$46,788",
          nonResidentTotal: "$86,058",
          sourceUrl: "https://fas.ucsd.edu/cost-of-attendance/undergraduates/index.html",
        },
        image: "./assets/uc-san-diego.jpg",
        imageAlt: "Geisel Library at UC San Diego",
        imageSource: "https://commons.wikimedia.org/wiki/File:Geisel_Library,_UCSD.jpg",
        summary:
          "UC San Diego is a selective coastal research campus with major strengths in computer science, engineering, biology, cognitive science, data science, medicine, oceanography, and international policy.",
        programs: [
          "Computer Science",
          "Data Science",
          "Bioengineering",
          "Cognitive Science",
          "Marine Biology",
          "Economics",
          "Political Science",
          "Public Health",
          "Visual Arts",
          "Global Policy",
        ],
        fit: [
          "Students interested in STEM, health, ocean science, or data-heavy fields",
          "Applicants who like a college system inside a large research university",
          "Students who want a coastal San Diego setting with serious research intensity",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/University_of_California,_San_Diego",
        programsUrl: "https://admissions.ucsd.edu/why/majors/index.html",
      },
      {
        id: "uc-santa-barbara",
        name: "University of California, Santa Barbara",
        shortName: "UC Santa Barbara",
        city: "Santa Barbara",
        region: "Goleta Coast",
        founded: 1909,
        type: "Public research university",
        admission: {
          year: "Fall 2025",
          rate: 38,
          displayRate: "38%",
          applicants: "110,173",
          admitted: "42,094",
          enrolled: "5,081",
        },
        coordinates: { lat: 34.4139, lon: -119.8489 },
        cost: {
          year: "2026-27",
          tuition: "$17,673",
          tuitionNumeric: 17673,
          onCampusHousing: "$13,203",
          onCampusFood: "$10,782",
          totalResident: "$50,946",
          nonResidentTotal: "$90,216",
          sourceUrl: "https://www.finaid.ucsb.edu/costs-estimated-aid/cost-attendance/ucsb-undergraduate-cost-attendance-budget",
        },
        image: "./assets/uc-santa-barbara.jpg",
        imageAlt: "Storke Tower and University Center at UC Santa Barbara",
        imageSource: "https://commons.wikimedia.org/wiki/File:UCSB_University_Center_and_Storke_Tower.jpg",
        summary:
          "UC Santa Barbara is a coastal research campus known for physics, engineering, environmental studies, economics, communication, biology, marine science, and a residential student culture near the Pacific.",
        programs: [
          "Physics",
          "Engineering",
          "Environmental Studies",
          "Economics",
          "Communication",
          "Biology",
          "Marine Science",
          "Psychological & Brain Sciences",
          "Film & Media Studies",
          "Statistics & Data Science",
        ],
        fit: [
          "Students who want a selective UC with a coastal residential setting",
          "Applicants interested in physics, engineering, environmental work, economics, or media",
          "Students who value research and campus life in equal measure",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/University_of_California,_Santa_Barbara",
        programsUrl: "https://admissions.sa.ucsb.edu/majors",
      },
      {
        id: "uc-santa-cruz",
        name: "University of California, Santa Cruz",
        shortName: "UC Santa Cruz",
        city: "Santa Cruz",
        region: "Monterey Bay",
        founded: 1965,
        type: "Public research university",
        admission: {
          year: "Fall 2025",
          rate: 72,
          displayRate: "72%",
          applicants: "66,393",
          admitted: "48,122",
          enrolled: "4,597",
        },
        coordinates: { lat: 36.9914, lon: -122.0609 },
        cost: {
          year: "2026-27",
          tuition: "$17,489",
          tuitionNumeric: 17489,
          onCampusHousingFood: "$21,477",
          offCampusHousingFood: "$21,522",
          totalResident: "$47,627",
          sourceUrl: "https://financialaid.ucsc.edu/managing-aid/budget-cost-to-attend/",
        },
        image: "./assets/uc-santa-cruz.jpg",
        imageAlt: "Aerial view of UC Santa Cruz and Santa Cruz",
        imageSource: "https://commons.wikimedia.org/wiki/File:UCSC_%26_Santa_Cruz_Aerial_view.jpg",
        summary:
          "UC Santa Cruz blends a residential college system with research strengths in computer science, game design, marine biology, environmental studies, astrophysics, psychology, and the arts.",
        programs: [
          "Computer Science",
          "Computer Game Design",
          "Marine Biology",
          "Environmental Studies",
          "Astrophysics",
          "Psychology",
          "Business Management Economics",
          "Film & Digital Media",
          "Molecular Biology",
          "Art",
        ],
        fit: [
          "Students who like forested residential colleges and a more experimental campus identity",
          "Applicants interested in computing, games, marine science, environmental studies, or creative fields",
          "Students who want access to Monterey Bay and Silicon Valley-adjacent opportunities",
        ],
        sourceUrl: "https://en.wikipedia.org/wiki/University_of_California,_Santa_Cruz",
        programsUrl: "https://admissions.ucsc.edu/programs",
      },
    ],
  },
  ...futureStateNames.map((name) => ({
    id: name.toLowerCase().replaceAll(" ", "-"),
    name,
    status: "empty",
    note: "Ready for future four-year colleges. Community colleges should stay excluded.",
    colleges: [],
  })),
];

const ivyLeagueColleges = [
  {
    id: "brown",
    name: "Brown University",
    shortName: "Brown",
    city: "Providence",
    stateName: "Rhode Island",
    region: "College Hill",
    founded: 1764,
    type: "Private Ivy League research university",
    admission: {
      year: "Latest published",
      rate: 6,
      displayRate: "~6%",
      applicants: "Highly selective",
      admitted: "Varies",
      enrolled: "Varies",
    },
    coordinates: { lat: 41.8268, lon: -71.4025 },
    cost: {
      year: "2026-27",
      tuition: "$74,568",
      tuitionNumeric: 74568,
      fees: "$3,084",
      onCampusHousing: "$10,710",
      onCampusFood: "$8,754",
      totalResident: "$99,984",
      sourceUrl: "https://finaid.brown.edu/estimate-cost-aid/cost",
    },
    image: "./assets/ivy-brown.jpg",
    imageAlt: "Front campus at Brown University",
    imageSource: "https://commons.wikimedia.org/wiki/File:Front_Campus,_Brown_University_(NBY_3393).jpg",
    summary:
      "Brown is known for its Open Curriculum, undergraduate academic freedom, strong humanities and sciences, public health, engineering, computer science, and a collaborative campus culture in Providence.",
    programs: [
      "Computer Science",
      "Applied Mathematics",
      "Economics",
      "International & Public Affairs",
      "Biology",
      "Public Health",
      "Engineering",
      "English",
      "Visual Art",
      "Cognitive Neuroscience",
    ],
    fit: [
      "Students who want a flexible curriculum with fewer distribution requirements",
      "Applicants interested in interdisciplinary work across humanities, social science, STEM, and public health",
      "Students who want a city campus with a smaller Ivy League feel",
    ],
    sourceUrl: "https://admission.brown.edu/",
    programsUrl: "https://www.brown.edu/academics/",
  },
  {
    id: "columbia",
    name: "Columbia University",
    shortName: "Columbia",
    city: "New York",
    stateName: "New York",
    region: "Morningside Heights",
    founded: 1754,
    type: "Private Ivy League research university",
    admission: {
      year: "Latest published",
      rate: 4,
      displayRate: "~4%",
      applicants: "Highly selective",
      admitted: "Varies",
      enrolled: "Varies",
    },
    coordinates: { lat: 40.8075, lon: -73.9626 },
    cost: {
      year: "2026-27 estimate",
      tuition: "$74,526",
      tuitionNumeric: 74526,
      fees: "See source",
      onCampusHousing: "$13,900",
      onCampusFood: "$8,800",
      totalResident: "$100,000+",
      sourceUrl: "https://sfs.columbia.edu/content/cost-attendance",
      note: "Columbia's official cost page blocked automated reading in this session; verify the latest exact billed charges from the source link.",
    },
    image: "./assets/ivy-columbia.jpg",
    imageAlt: "Low Memorial Library at Columbia University",
    imageSource: "https://commons.wikimedia.org/wiki/File:2014_Columbia_University_Low_Memorial_Library_from_front.jpg",
    summary:
      "Columbia pairs a Core Curriculum with New York City access, strong humanities, journalism, political science, engineering, economics, data science, and global affairs pathways.",
    programs: [
      "Political Science",
      "Economics",
      "Computer Science",
      "Data Science",
      "Engineering",
      "English",
      "Neuroscience",
      "Film & Media Studies",
      "Urban Studies",
      "Sustainable Development",
    ],
    fit: [
      "Students who want a structured core curriculum in a major city",
      "Applicants interested in journalism, policy, finance, media, data, or global affairs",
      "Students comfortable with a dense urban campus and fast-paced opportunities",
    ],
    sourceUrl: "https://undergrad.admissions.columbia.edu/",
    programsUrl: "https://www.college.columbia.edu/academics",
  },
  {
    id: "cornell",
    name: "Cornell University",
    shortName: "Cornell",
    city: "Ithaca",
    stateName: "New York",
    region: "Finger Lakes",
    founded: 1865,
    type: "Private Ivy League research university",
    admission: {
      year: "Latest published",
      rate: 8,
      displayRate: "~8%",
      applicants: "Highly selective",
      admitted: "Varies",
      enrolled: "Varies",
    },
    coordinates: { lat: 42.4534, lon: -76.4735 },
    cost: {
      year: "2026-27",
      tuition: "$73,946",
      tuitionNumeric: 73946,
      fees: "$1,024",
      onCampusHousing: "$13,744",
      onCampusFood: "$7,604",
      totalResident: "$99,734",
      sourceUrl: "https://finaid.cornell.edu/cost-to-attend",
    },
    image: "./assets/ivy-cornell.jpg",
    imageAlt: "Cornell west campus from McGraw Tower",
    imageSource: "https://commons.wikimedia.org/wiki/File:Cornell_West_Campus_from_McGraw_Tower.jpg",
    summary:
      "Cornell is the largest Ivy by undergraduate breadth, with strong engineering, computer science, agriculture, business, hotel administration, architecture, life sciences, and policy programs.",
    programs: [
      "Engineering",
      "Computer Science",
      "Business",
      "Hotel Administration",
      "Architecture",
      "Agriculture & Life Sciences",
      "Information Science",
      "Biological Sciences",
      "Economics",
      "Public Policy",
    ],
    fit: [
      "Students who want Ivy League academics with a larger university structure",
      "Applicants interested in applied fields, engineering, hospitality, agriculture, business, or design",
      "Students who like a college-town setting with many specialized schools",
    ],
    sourceUrl: "https://admissions.cornell.edu/",
    programsUrl: "https://www.cornell.edu/academics/",
  },
  {
    id: "dartmouth",
    name: "Dartmouth College",
    shortName: "Dartmouth",
    city: "Hanover",
    stateName: "New Hampshire",
    region: "Upper Valley",
    founded: 1769,
    type: "Private Ivy League research college",
    admission: {
      year: "Latest published",
      rate: 6,
      displayRate: "~6%",
      applicants: "Highly selective",
      admitted: "Varies",
      enrolled: "Varies",
    },
    coordinates: { lat: 43.7044, lon: -72.2887 },
    cost: {
      year: "2026-27",
      tuition: "$71,697",
      tuitionNumeric: 71697,
      fees: "$2,157",
      onCampusHousing: "$13,032",
      onCampusFood: "$8,496",
      totalResident: "$98,427",
      sourceUrl: "https://financialaid.dartmouth.edu/cost-attendance/cost-attendance-2026-2027",
    },
    image: "./assets/ivy-dartmouth.jpg",
    imageAlt: "Baker-Berry Library at Dartmouth College",
    imageSource: "https://commons.wikimedia.org/wiki/File:Dartmouth_College_campus_2007-09-24_Baker-Berry_Library_01.JPG",
    summary:
      "Dartmouth emphasizes undergraduate teaching, a flexible quarter calendar, liberal arts depth, strong economics, government, engineering, computer science, and outdoor-oriented campus life.",
    programs: [
      "Economics",
      "Government",
      "Computer Science",
      "Engineering Sciences",
      "Biology",
      "Psychology",
      "Environmental Studies",
      "Native American Studies",
      "Film & Media Studies",
      "Quantitative Social Science",
    ],
    fit: [
      "Students who want undergraduate focus and close faculty access",
      "Applicants who like liberal arts plus research and engineering options",
      "Students who value a small college-town environment and outdoor access",
    ],
    sourceUrl: "https://admissions.dartmouth.edu/",
    programsUrl: "https://home.dartmouth.edu/academics",
  },
  {
    id: "harvard",
    name: "Harvard University",
    shortName: "Harvard",
    city: "Cambridge",
    stateName: "Massachusetts",
    region: "Greater Boston",
    founded: 1636,
    type: "Private Ivy League research university",
    admission: {
      year: "Latest published",
      rate: 3,
      displayRate: "~3%",
      applicants: "Highly selective",
      admitted: "Varies",
      enrolled: "Varies",
    },
    coordinates: { lat: 42.3744, lon: -71.1169 },
    cost: {
      year: "2026-27",
      tuition: "$62,226",
      tuitionNumeric: 62226,
      fees: "$6,216",
      onCampusHousing: "$14,250",
      onCampusFood: "$8,942",
      totalResident: "$95,134-$100,134",
      sourceUrl: "https://college.harvard.edu/financial-aid/how-aid-works",
    },
    image: "./assets/ivy-harvard.jpg",
    imageAlt: "Holworthy Gate at Harvard Yard",
    imageSource: "https://commons.wikimedia.org/wiki/File:Holworthy_Gate_(Harvard_Yard)_-_IMG_8982.JPG",
    summary:
      "Harvard offers broad liberal arts and research pathways, with major strengths in economics, government, life sciences, computer science, engineering, public policy, history, and global studies.",
    programs: [
      "Economics",
      "Government",
      "Computer Science",
      "Applied Mathematics",
      "Engineering Sciences",
      "Molecular & Cellular Biology",
      "History",
      "Psychology",
      "Social Studies",
      "Statistics",
    ],
    fit: [
      "Students aiming for an extremely selective research university with broad academic reach",
      "Applicants interested in leadership, research, public service, science, policy, or entrepreneurship",
      "Students who want access to Boston and Cambridge academic networks",
    ],
    sourceUrl: "https://college.harvard.edu/admissions",
    programsUrl: "https://college.harvard.edu/academics",
  },
  {
    id: "princeton",
    name: "Princeton University",
    shortName: "Princeton",
    city: "Princeton",
    stateName: "New Jersey",
    region: "Central New Jersey",
    founded: 1746,
    type: "Private Ivy League research university",
    admission: {
      year: "Latest published",
      rate: 4,
      displayRate: "~4%",
      applicants: "Highly selective",
      admitted: "Varies",
      enrolled: "Varies",
    },
    coordinates: { lat: 40.3431, lon: -74.6551 },
    cost: {
      year: "2026-27",
      tuition: "$68,140",
      tuitionNumeric: 68140,
      fees: "$314",
      onCampusHousing: "$13,010",
      onCampusFood: "$9,110",
      totalResident: "$94,624",
      sourceUrl: "https://admission.princeton.edu/cost-aid/fees-payment-options",
    },
    image: "./assets/ivy-princeton.jpg",
    imageAlt: "Nassau Hall at Princeton University",
    imageSource: "https://commons.wikimedia.org/wiki/File:Nassau_Hall_in_the_distance,_Princeton_University,_Princeton_NJ.jpg",
    summary:
      "Princeton is known for undergraduate focus, senior thesis work, strong financial aid, engineering, public policy, economics, math, physics, computer science, and humanities.",
    programs: [
      "Economics",
      "Computer Science",
      "Public & International Affairs",
      "Engineering",
      "Mathematics",
      "Physics",
      "Molecular Biology",
      "Politics",
      "Architecture",
      "English",
    ],
    fit: [
      "Students who want undergraduate-focused research and close advising",
      "Applicants interested in thesis-driven work, policy, math, science, engineering, or humanities",
      "Students who want a residential campus between New York and Philadelphia",
    ],
    sourceUrl: "https://admission.princeton.edu/",
    programsUrl: "https://www.princeton.edu/academics",
  },
  {
    id: "penn",
    name: "University of Pennsylvania",
    shortName: "Penn",
    city: "Philadelphia",
    stateName: "Pennsylvania",
    region: "University City",
    founded: 1740,
    type: "Private Ivy League research university",
    admission: {
      year: "Latest published",
      rate: 5,
      displayRate: "~5%",
      applicants: "Highly selective",
      admitted: "Varies",
      enrolled: "Varies",
    },
    coordinates: { lat: 39.9522, lon: -75.1932 },
    cost: {
      year: "2026-27",
      tuition: "$65,670",
      tuitionNumeric: 65670,
      fees: "$8,308",
      onCampusHousing: "$13,644",
      onCampusFood: "$6,960",
      offCampusHousing: "$12,978",
      offCampusFood: "$5,988",
      totalResident: "$99,082",
      sourceUrl: "https://srfs.upenn.edu/costs-budgeting/undergraduate-cost-attendance",
    },
    image: "./assets/ivy-penn.jpg",
    imageAlt: "College Hall at the University of Pennsylvania",
    imageSource: "https://commons.wikimedia.org/wiki/File:North_facade_of_College_Hall,_Penn_Campus.jpg",
    summary:
      "Penn combines Ivy League liberal arts with pre-professional strength, especially Wharton business, nursing, engineering, economics, communication, political science, and health-related fields.",
    programs: [
      "Business",
      "Economics",
      "Nursing",
      "Engineering",
      "Computer Science",
      "Communication",
      "Political Science",
      "Biology",
      "Finance",
      "Urban Studies",
    ],
    fit: [
      "Students who want an urban Ivy with strong business and pre-professional pathways",
      "Applicants interested in interdisciplinary study across Wharton, engineering, nursing, and arts and sciences",
      "Students who want Philadelphia access and a larger undergraduate environment",
    ],
    sourceUrl: "https://admissions.upenn.edu/",
    programsUrl: "https://www.upenn.edu/academics",
  },
  {
    id: "yale",
    name: "Yale University",
    shortName: "Yale",
    city: "New Haven",
    stateName: "Connecticut",
    region: "Downtown New Haven",
    founded: 1701,
    type: "Private Ivy League research university",
    admission: {
      year: "Latest published",
      rate: 4,
      displayRate: "~4%",
      applicants: "Highly selective",
      admitted: "Varies",
      enrolled: "Varies",
    },
    coordinates: { lat: 41.3163, lon: -72.9223 },
    cost: {
      year: "2026-27",
      tuition: "$72,500",
      tuitionNumeric: 72500,
      fees: "$185",
      onCampusHousing: "$12,080",
      onCampusFood: "$9,520",
      totalResident: "$97,985",
      sourceUrl: "https://finaid.yale.edu/coa",
    },
    image: "./assets/ivy-yale.jpg",
    imageAlt: "Yale Old Campus courtyard and Harkness Tower",
    imageSource: "https://commons.wikimedia.org/wiki/File:2014-04-17-Yale-Old-Campus-Courtyard-Harkness-Tower.jpg",
    summary:
      "Yale is known for residential colleges, humanities, arts, social sciences, political science, economics, global affairs, biology, computer science, and strong undergraduate advising.",
    programs: [
      "Economics",
      "Political Science",
      "Global Affairs",
      "Computer Science",
      "History",
      "English",
      "Molecular Biophysics & Biochemistry",
      "Psychology",
      "Theater Studies",
      "Statistics & Data Science",
    ],
    fit: [
      "Students who want residential college life inside a major research university",
      "Applicants interested in humanities, arts, policy, global affairs, sciences, or data",
      "Students who value strong advising and a campus-centered undergraduate experience",
    ],
    sourceUrl: "https://admissions.yale.edu/",
    programsUrl: "https://www.yale.edu/academics",
  },
];
